"""empty message

Revision ID: a0e70a3136f4
Revises: c618aa88f390
Create Date: 2020-07-18 09:10:54.832706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e70a3136f4'
down_revision = 'c618aa88f390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'venue_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
