import os
SECRET_KEY = os.urandom(32)

# Grabs the folder where the script runs.
basedir = os.path.abspath(os.path.dirname(__file__))

auth0_config = {
    "AUTH0_DOMAIN" : os.getenv('DATABASE_URL'),
    "ALGORITHMS" :   os.getenv('ALGORITHMS'),
    "API_AUDIENCE" : os.getenv('API_AUDIENCE')
}



bearer_tokens = {
    "casting_assistant" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVlbDRPRkdvd3ZocUhkQUFNalFkSCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQ1MTQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjI5YjQ1MjVjODQ4ZjAwMzdjNDZhNWEiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTU5NjYxODEwNSwiZXhwIjoxNTk2NjI1MzA1LCJhenAiOiJCM1RaMldVeGZMQ1FtdmQ5OHRtU2hNWURJUzRhNG02RCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiXX0.uvJOJvSTCzV0L9hd2RVK1-mbx5PgsbRjT-02HrJqV0VIAXVi7EG9EnewQLTjuDY-JKYfhAlBdK2o2KMUIZ6F_4QTNy3tXTWUOJJdPkmc3noUxrB3V2sVDC4jdRogt6U-95KJaJMd0uqkmOn06a_lxsyyep11aqirJxx2nytB3nQH-7cdc64yWUkC7Y2BN2DBucmg_R8ICDkkvyVAXMhA2rU6SLle8uYEpjM4Bi9YADUHv7fOFmsPJD2aGdkJJ3XlHghxU1jJx9f-enzYC_lo0DUF79J1MxhGMhY-5nMOO0vsPh4lbe8qHK4_eHabFKFiA8Ob7d_Nl3RMMh8uYxLf7Q",
    "executive_producer" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVlbDRPRkdvd3ZocUhkQUFNalFkSCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQ1MTQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjI0ZmQ3ZjMxYmVkNTAwOTkwNDE3MzQiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTU5NjYxNzkzMiwiZXhwIjoxNTk2NjI1MTMyLCJhenAiOiJCM1RaMldVeGZMQ1FtdmQ5OHRtU2hNWURJUzRhNG02RCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImRlbGV0ZTptb3ZpZXMiLCJnZXQ6YWN0b3JzIiwiZ2V0Om1vdmllcyIsInBhdGNoOmFjdG9ycyIsInBhdGNoOm1vdmllcyIsInBvc3Q6YWN0b3JzIiwicG9zdDptb3ZpZXMiXX0.wW2jdPxG0cFcYcZQgctXBOhszbDEm-rQiXaOoj9KLN0mqrbq0cGQ4qg7nSBOkcn9-NvbsIGk6uiSJo-ORm972VcVfgCrIOFoZNainsOpAf4bpeKdGBu0aD_bePYjJt36BB32V4130jz4G_3NazTNHlaLeICKdDSus0izIYxsTnM4avcCuE3Do72MPSC7sIj_n1swcA_9HVvReknrDEKJL4_ohGaDWGGEdOgZDYzTI2l0VqfiEcXrUCXdrWyIbntwAnN7kWknA7FMJk0kwh7CAjuUXXmPHfdcdrMVG2YifkrCe7vSM_K9zrf19_qqWQCk0RMYlxyLLCjt-2NjZiC43A",
    "casting_director" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVlbDRPRkdvd3ZocUhkQUFNalFkSCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQ1MTQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjI3MTVjYjMxYmVkNTAwOTkwNDI5MzYiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTU5NjYxODA0NSwiZXhwIjoxNTk2NjI1MjQ1LCJhenAiOiJCM1RaMldVeGZMQ1FtdmQ5OHRtU2hNWURJUzRhNG02RCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImdldDphY3RvcnMiLCJnZXQ6bW92aWVzIiwicGF0Y2g6YWN0b3JzIiwicGF0Y2g6bW92aWVzIiwicG9zdDphY3RvcnMiXX0.Pm--G2r1_JB_1mTyowIEB-az_XtKwHkU3PavXSn6lAQGRSyok60SQZrONAvB33us9OlygkX2MCrsY8A0HJKl3qAkycT7xIK77XR8B8avxWnq3emtuWeQo6NzLcFN9-kvNFeBfl6w8QdlD5f6V3QoSuTGje9Ly9sSma02o9Ql9fy1bqKjKA1K1VcyxRMiqcVWBBUGN8lqQriqr-KPRaj85JaWwL8YiAA1lj3Bx7b2wNDHEbZlCRo7w6JL3eNkXk566l_vmyNg6TQfyJgs89b_SrTXnsskoMikL71-JsBZ2Y8ME3x1-AQGBnVoWf0dSHzA9ixxekCe7LVqVwkvBMAXeQ"}
os.environ['casting_assistant_auth'] = bearer_tokens['casting_assistant']
os.environ['casting_director_auth'] = bearer_tokens['casting_director']
os.environ['executive_producer_auth'] = bearer_tokens['executive_producer']

#print(auth0_config)