import os
SECRET_KEY = os.urandom(32)

# Grabs the folder where the script runs.
basedir = os.path.abspath(os.path.dirname(__file__))

auth0_config = {
    "AUTH0_DOMAIN" : os.getenv('DATABASE_URL'),
    "ALGORITHMS" :   os.getenv('ALGORITHMS'),
    "API_AUDIENCE" : os.getenv('API_AUDIENCE')
}

database_setup = {
   "database_name_production" : "capstone_local_test_db",
   "user_name" : "postgres", # default postgres user name
   "password" : "postgres", # if applicable. If no password, just type in None
   "port" : "localhost:5432" # default postgres port
}


bearer_tokens = {
    "casting_assistant" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVlbDRPRkdvd3ZocUhkQUFNalFkSCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQ1MTQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjI5YjQ1MjVjODQ4ZjAwMzdjNDZhNWEiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTU5NjY1MTUxOSwiZXhwIjoxNTk2NzM3OTE5LCJhenAiOiJCM1RaMldVeGZMQ1FtdmQ5OHRtU2hNWURJUzRhNG02RCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiXX0.aiyYi0vimi6hTbsLeSeu0o99ExYtFzqqA8khJiDDAtBuGtrfCjthh-_xGYwdoCZm9nkf1Zjk4DLs9_lTyIDQXaV_5uBeTtIg_R2h5wllxMl7PeleHonmV9mKgrguvJqQqx5-wTe0FBwsJ9MCgpLITPyFzNmpAzVxSMzD_VqUwgIhIs38qYfJW9FpY1Fj5F24AajfEQG4VnT-Bb6IJRSaMpCzN4O-DrQLysLk-Rok1wU43Qtel2bBlIq5-JqJYsECVDaudojv-8YSlqluJnTqNYE6gpefYIUtYQb_Cizk8oLnh4Ll-dYvU_wtoYPC8B36IiJYkFbEI0Aks3EFc_OuWg",
     "executive_producer" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVlbDRPRkdvd3ZocUhkQUFNalFkSCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQ1MTQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjI0ZmQ3ZjMxYmVkNTAwOTkwNDE3MzQiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTU5NjY1MTI2NCwiZXhwIjoxNTk2NzM3NjY0LCJhenAiOiJCM1RaMldVeGZMQ1FtdmQ5OHRtU2hNWURJUzRhNG02RCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImRlbGV0ZTptb3ZpZXMiLCJnZXQ6YWN0b3JzIiwiZ2V0Om1vdmllcyIsInBhdGNoOmFjdG9ycyIsInBhdGNoOm1vdmllcyIsInBvc3Q6YWN0b3JzIiwicG9zdDptb3ZpZXMiXX0.KPw1kGIoXlSz6sdO9qQi-oUGHMs_Ua9jFlBNNWkAfzfH93M4Zgg2HI9jDYtnC2dDlC7wCqy_0lLUQeyEo0ZS81RPc_UUglUHhTQiAdzsnxXuDF5_LsNQgO80bmytWphNnT-okD75weeT3F_auCQ19b-wIrFyiXEXsHzlqcMen57zmpyb4kJY0oZ-4vo2GkPCf1BpFRyKvqmZawfnXFHzU2Xnx32O3oJvwin5xTgiSQgxyn4dnTs_LK85Q34o9nuizzIXuibf1aKHvCGADfG7jusT8VK6ZwK9fLYUF8hDk_SwEJqxoWv0VVHG5dtnp_gi3yGTmrLP-PEhN9VSmXr32Q",
    "casting_director" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVlbDRPRkdvd3ZocUhkQUFNalFkSCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQ1MTQxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjI3MTVjYjMxYmVkNTAwOTkwNDI5MzYiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTU5NjY1MTQxMywiZXhwIjoxNTk2NzM3ODEzLCJhenAiOiJCM1RaMldVeGZMQ1FtdmQ5OHRtU2hNWURJUzRhNG02RCIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImdldDphY3RvcnMiLCJnZXQ6bW92aWVzIiwicGF0Y2g6YWN0b3JzIiwicGF0Y2g6bW92aWVzIiwicG9zdDphY3RvcnMiXX0.b9FtjKFBkjZA8pSvzVzdxxNzoMziJInzeqAqSQ860n-ZZ3hvqf7QW4wxbFgUXAplVS9qBHULEIbQp5O0Qeluza_UpM7P_XO5VZ22tBA6lnz0X5MZbtZCUhu6odvTDwyaV5BlMWGsewPnytxd9znoBW_1rvwggeaQlB790zn6F1JrBv_DY4tH7rzKsjOeKyDXFg-TGPXSMrTdG7nGwBT6F_FPRdJqqCIEEpV2xpO1KyM3CpMzD4erYVjATRYS_phQxZFGEZsJ6eNRirblJOpE_35OIKOVfYnTXhCP2t2kXqZ-ia868e1ZQ5B9WaYd2litMCiVX04oBYJviEqbiZlZKA"}
os.environ['casting_assistant_auth'] = bearer_tokens['casting_assistant']
os.environ['casting_director_auth'] = bearer_tokens['casting_director']
os.environ['executive_producer_auth'] = bearer_tokens['executive_producer']
